name: DffEnchantz
version: 1.0
author: joonatoona
main: com.digitalfishfun.dffenchantz.Main
commands:
  enchant:
    description: Open the enchantment shop
  givebook:
    description: Give the specified enchantment book